[package]
name = "framescope"
version = "0.2.1"
edition = "2021"
description = "Schlanker, portabler Videoplayer für frame-genaue Analyse"
license-file = "LICENSE"
rust-version = "1.88"

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
eframe = { version = "0.36", default-features = false, features = ["glow", "default_fonts"] }
ffmpeg-next = { version = "9", default-features = false, features = ["codec", "format", "software-scaling", "software-resampling"] }
rfd = "0.17"
cpal = "0.18"
image = { version = "0.25", default-features = false, features = ["png"] }
bytemuck = "1"
egui-phosphor = { version = "0.14", features = ["regular", "fill"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
opt-level = 3

[build-dependencies]
embed-resource = "3"
